apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: network-shared-directory
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: cp4a-file-retain-bronze-gid
 
