apiVersion: v1
kind: Secret
metadata:
  name: icp4adeploy-bas-admin-secret
type: Opaque
stringData:
  dbUsername: "db2inst1"
  dbPassword: "passw0rd"
---
apiVersion: v1
kind: Secret
metadata:
  name: playback-server-admin-secret
type: Opaque
stringData: 
  AE_DATABASE_PWD: "passw0rd"
  AE_DATABASE_USER: "db2inst1"
  REDIS_PASSWORD: "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: resource-registry-admin-secret
type: Opaque
stringData:
  rootPassword: "passw0rd"
  readUser: "reader"
  readPassword: "readerpwd"
  writeUser: "writer"
  writePassword: "writerpwd"
---
apiVersion: v1
kind: Secret
metadata:
  name: ae-secret-credential
type: Opaque
stringData: 
  AE_DATABASE_PWD: "passw0rd"
  AE_DATABASE_USER: "db2inst1"
  REDIS_PASSWORD: "password"