apiVersion: v1
kind: PersistentVolume
metadata:
  name: cmis-cfgstore-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  nfs:
    path: /opt/nfs2/cmis/configDropin/overrides
    server: <NFS SERVER>
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cmis-cfgstore-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cmis-cfgstore
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: cmis-cfgstore-pv
  volumeName: cmis-cfgstore-pv
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cmis-logstore-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  nfs:
    path: /opt/nfs2/cmis/logs
    server: <NFS SERVER>
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cmis-logstore-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cmis-logstore
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: cmis-logstore-pv
  volumeName: cmis-logstore-pv
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
